FROM rocker/rstudio:3.6.1

# install additional system dependencies
RUN apt-get update && apt-get install -y libxml2-dev zlib1g-dev libgit2-dev


# set CRAN repo to the RStudio mirror
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site

# when R runs in the container it should automatically use the packrat library
RUN echo '.libPaths("/home/rstudio/packrat/lib/x86_64-pc-linux-gnu/3.6.1")' >> /usr/local/lib/R/etc/Rprofile.site

# install packrat
RUN Rscript -e "install.packages('packrat')"

# install hugo
WORKDIR /tmp
RUN wget https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
RUN dpkg -i /tmp/hugo_0.56.3_Linux-64bit.deb

# entrypoint to the container (starts Rstudio)
CMD ["/init"]
