---
title: Let's get started!
author: Stefan Schliebs
date: '2018-03-20'
slug: let-s-get-started
categories: []
tags: []
---

After years of working in academic and commercial environments, I really came to value best practice. Being immersed in the process of solving complex problems with tools that are both elegant and efficient to use is still one of the most rewarding activities in my day-to-day work as a data scientist. Obviouly there is more than one approach to a problem, but in this blog we will share our experience about the tools, practices and workflows that we think to be the most useful for everyday use.

<!--more-->

Unfortunately there isn't a concrete definition of what best practice means and there is a myriad of tools in the market that make it difficult to decide which one to use. Our approach to teaching is highly opionated. We recommend best practices that are battle tested and have worked for us in a fast-paced modern analytics environment. It is our mission to make data deliverables fully reproducible, decrease manual labor and consequently reduce errors and improve productivity of data professionals. 

Let's raise the bar!
